version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./data:/srv
      - ./config.json:/config.json
      - ./database.db:/etc/database.db
    networks:
      - proxy
networks:
  proxy:
    external: true
